### ISSUE TITLE
Is there a french version of this documentation ?

### ISSUE THREAD

**Issue by denis78730** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#117]
Hi, Is there a french version of this documentation ?
If the answer is no, what do you think if I make it ?
Regards,
Denis

**Comment by ChristopherA** [comment]
There isn't a French version of this course, and we would welcome one. However, be aware our goal is to revise this course this summer for Bitcoin 0.20 so there will be some big changes coming.

Thanks!

**Comment by denis78730** [comment]
Perfect. I've got the two first chapters ready. Can you give me the right to commit them ?

**Comment by ChristopherA** [comment]
a) We've moved the repo officially to https://github.com/BlockchainCommons/

b) Put your translations under ./fr/

b) Submit a PR with your translation to that repo (i.e. fork it to your own repo, make the changes there, and then do a PR back). I'll have someone evaluate it. If it looks good we can give you more privileges. 

Thanks for offering to help!!

-- Christopher Allen

**Comment by denis78730** [comment]
Done today using Github Desktop, with the branch FR but I do not see it here.
Please let me know if you've seen something on your side.

Denis

**Comment by ChristopherA** [comment]
I'm not seeing a pull request, but the problem may be that we moved the repo from GitHub/ChristopherA to GitHub/BlockchainCommons.

These are the steps I advise.

* save your /fr directory elsewhere
* delete the forked /learning repo from both your personal GitHub account and from your computer.
* fork the BlockchainCommons/learning repo to your personal GitHub repo
* use GitHub desktop to clone it locally on your computer.
* Add your /fr directory locally and push it back to your GitHub repo.
* You should now be able to create the PR using the UI in the GitHub repo.

I has been my long-term goal to document how to do this more easily with tools like GitHub Desktop, but I have not had the time yet. Let me know if you have difficulty with the very abbreviated version of how to do so that I describe above.

-- Christopher Allen

**Comment by denis78730** [comment]
All done, and pushed under GitHub Desktop in a new branch called "FR"
But I do not see it under GitHub Website when doing Pull Request (I see only master and kallewoof-patch-1)
Denis

**Comment by denis78730** [comment]
New attempt. While clicking of "Publish your branch" I get this message
"It looks like you don't have write access to "blockchaincommons/Learning...". If you should, please check with a repository administrator.
There are two buttons : "Fork this repository" and "Cancel".
What should I do ?

**Comment by ChristopherA** [comment]
It sounds like you did not fork the leaning repo to your GitHub account
first. You can the add your own changes to your own repo, and after you’ll
see a button to submit a pull request back to upstream master.

— Christopher Allen

**Comment by shannona** [comment]
See PR#121.
