### ISSUE TITLE
Spanish Translation of v2 of #LBftCL

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#214]
There has been some renewed interest in 2021 for a Spanish translation of this course, to be put in an /es/ subdirectory. This is a good time for it as the course is somewhat stable, the next planned additions will be additional content. HOWEVER, the course will have to be massively re-worked post Taproot/Schnorr in 2022, and hopefully any translation of v2 is complete before then, and people will be interested in helping translate v3.

This issue is track discussions among those interested in being involved.

**Comment by csralvall** [comment]
@ChristopherA I'm interested as I stated [here](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/commit/a84f1f7574954a304f8e19cc9d4b80c290b9f379).

**Comment by icculp** [comment]
Hey @csralvall those are all great reasons to contribute, and mirror my own motivations. We are coordinating in signal mostly, using hackmd to keep track of chapters. Currently chapters up to 10 are spoken for or finished/ready for review, but chapters 11 and on are unspoken for. We are making steady progress so that may change soon. You don't need to work every day, we are all volunteers here, so I think that as long as you contribute the amount you express to commit to then we are of course happy to accept the help!

We have so far agreed to use third person/formal tone in translation. Also, some terms may not transliterate directly or have unique translations, so feel free to ask the group for clarification if need be. Chapter links we'll wait to translate last, so as to avoid broken links in the mean time, and as a way to note final completion on translated chapters. 

Request to join the group here:
https://signal.group/#CjQKIM7T5pOhrl1K0ZugH4ejejOZeejV7GmkaeoiXSOZRv3xEhDW0w-7yfX92CtYypk5aCOg

Hope to see you there!

**Comment by shannona** [comment]
We've got plenty of other venues for discussion, so closing this old issue.
