### ISSUE TITLE
Tracking releases for translation

### ISSUE THREAD

**Issue by icculp** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#438]
During the translation into Spanish there has been a little bit of confusion as some chapters were translated based on the latest commits in the master branch, which is technically now farther along and different from Release 2.0.1 which was supposed to be our original target. The README in the master branch reflects 2.0.1, but this actual release is many months old and for example does not include the new inserted chapter 15, but going by the readme might lead one to believe that 2.0.1 and the current master branch are the same, so maybe the master readme shouldn't reflect the release number as the next merged commit would make it a different release.

I think those of us translating as a small team didn't realize the need to communicate/enforce this initially. This has created challenges during translation as we are translating towards a moving target, and keeping track of changes and what's left to do becomes increasingly complicated as more updates are reflected in master. There should be a sort of onboarding process for each new contributor, to ensure that they understand the stationary target of the release to translate to.

**Comment by shannona** [comment]
This was essentially my mistake in not saying to use 2.0.0 as the benchmark, as 2.0.1 was still raw. I'm going to add to the translation instructions momentarily, to use the last milestone for future translations.

For this particular translation project (the spanish & portuguese translations that we are closing in on finishing), I plan to:

1.) Wait until all PRs are closed related to translations
2.) Do a long-delayed final polish of the i2p section
3.) Create a 2.0.2 milestone
4.) Let translators know, so that they can review 2.0.1->2.0.2 updates if they wish
5.) After giving a few weeks for any final changes, incorporate and publish translations
