### ISSUE TITLE
Does this guides apply for signet too

### ISSUE THREAD

**Issue by Blazing-Mike** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#449]
I'm am currently running my Bitcoin core on signet( it's more realistic than testnet and has additional block validation) . Does the instructions in the tutorial applies to signet too?

**Comment by shannona** [comment]
The tutorial in its current form largely predates signet and is intended for use mainly with testnet. However, signet is largely the same as testnet, with some difference in how blocks are produced. I suspect that the user experience as depicted in the tutorial is largely or entirely the same, it's just untested at the moment.

**Comment by ChristopherA** [comment]
@kallewoof is there anything in particular about signet we should add to the current edition of the course? We’ll cover more advanced signet uses in v2, but we have this question now.

**Comment by kallewoof** [comment]
Signet is streamlined for new users testing out, including the getcoins.sh script in contrib/signet. I would personally swap out testnet for signet, and add a section on getting coins using the aforementioned script to get started. Testnet is obsolete in this context (it is only useful for testing mining hardware, and even that is dubious, as you'd preferably want the off chance of getting bitcoin rather than testnet coins if your miner finds a block).
